//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steamjazz.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Steamjazz.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatons in SteamJazz are divided into two distinct groups.
        ///Some automatons are so simple that sorting boxes into piles
        ///causes them difficulty, whereas other automatons have no
        ///trouble making independent decisions while adventuring, What
        ///makes these two groups apart is the CIC, or the Crystal
        ///Intelligence Clockwork. A CIC is a small intelligence
        ///clockwork mechanism designed to be added into any kind of
        ///automaton for greater intelligence and more independent action.
        ///It is possible for any kind of a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Automaton {
            get {
                return ResourceManager.GetString("Automaton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatons in SteamJazz are divided into two distinct groups.
        ///Some automatons are so simple that sorting boxes into piles
        ///causes them difficulty, whereas other automatons have no
        ///trouble making independent decisions while adventuring, What
        ///makes these two groups apart is the CIC, or the Crystal
        ///Intelligence Clockwork. A CIC is a small intelligence
        ///clockwork mechanism designed to be added into any kind of
        ///automaton for greater intelligence and more independent action.
        ///It is possible for any kind of a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Automatons {
            get {
                return ResourceManager.GetString("Automatons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STR +1, CON +1, EMP -1
        ///
        ///Basic automaton packages:
        ///
        ///Assistant / Servant
        ///Initial skill ranks: Profession (any) 2, Negotiate 1, Knowledge:
        ///Mathematics 1
        ///10 CP can be used to buy ranks in the following skills:
        ///Appraise, Clockwork, Craft (any), Knowledge (Mathematics),
        ///Negotiate, Persuade, Profession (any).
        ///
        ///Guard
        ///Initial skill ranks: Melee (Balanced) 2, Listen 1, Spot 1
        ///10 CP can be used to buy ranks in the following skills:
        ///Athletics, Block, Brawl, Clockwork, Handguns, Intimidate,
        ///Listen, Melee  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Basic {
            get {
                return ResourceManager.GetString("Basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMP -1, CHA -2, allocate +2 to one of the following attributes:
        ///STR, CON, DEX, REF, WIT and +1 to another attribute from
        ///the list.
        ///Animal Handling +1
        ///Advantage: Alertness
        ///Advantage: Keen Sense of Smell
        ///Must purchase at least one Advantage: Natural Weapon.
        ///Must purchase at least one of the following advantages:
        ///Hardened Skin, Low-light Vision, Keen Hearing and Keen
        ///Sense of Sight.
        ///
        ///Instinctive behavior: All beastfolk react instinctively to sudden,
        ///unexpected loud noises and sudden, unexpected mov [rest of string was truncated]&quot;;.
        /// </summary>
        public static string beastfolk {
            get {
                return ResourceManager.GetString("beastfolk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CON +1
        ///Initial skill ranks: Survival 2, Animal Handling 1, Brawl 1
        ///15 CP can be used to buy ranks in the following skills: Animal
        ///Handling, Archery, Athletics, Brawl, Climb, First Aid,
        ///Knowledge (Astrology), Knowledge (Folklore), Knowledge
        ///(Zoology), Listen, Melee (Balanced), Melee (Powerful), Sense
        ///Motive, Spot, Stealth, Survival, Track, or to the Animal
        ///Empathy advantage.
        ///
        ///
        ///The beastfolk originate from the Shadewood Forest in Victora,
        ///and this background represents those beastfolk who have been [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BeastfolkBack {
            get {
                return ResourceManager.GetString("BeastfolkBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost to play: 15CP
        ///
        ///STR -1, CON -1, INT +1, CHA +1, EMP +1
        ///Advantage: Bilingual
        ///Initial skill ranks: Etiquette 3, Cooking 2, Negotiate 2,
        ///Profession: Waiter 2
        ///10 CP can be used to buy ranks in the following skills:
        ///Clockwork, Cooking, Negotiate, Etiquette, First Aid, Language
        ///(any), Law (any), Leadership, Listen, Persuade, Search, Sense
        ///Motive, Spot.
        ///
        ///Models:
        ///Colman Inc CCB-02 Butler, commonly referred to as &quot;Charles&quot;
        ///or &quot;Charles B-02&quot;
        ///Colman Inc CCB-03 Maid, commonly referred to as
        ///“Charlott [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Butler {
            get {
                return ResourceManager.GetString("Butler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Careers represent your character’s profession and the skills
        ///required to be successful in it. Each career contains 12 skills
        ///that can be considered essential to the career. You must spend
        ///half of your starting CP to buy ranks in these Career Skills at
        ///character creation. You do not have to purchase ranks in all
        ///career skills if you think your character is not going to need all
        ///of them.
        ///Career names do not necessarily represent the exact profession
        ///of a character; instead, they are broader descriptor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost to play: 5CP
        ///
        ///STR +1, CON +2, CHA -1, EMP -1
        ///Initial STR and CON must be at least 12.
        ///Upgrade: Medium Plating, AV 4
        ///Initial skill ranks: Melee (Balanced) 3, Law (local) 2,
        ///Intimidate 1
        ///10 CP can be used to buy ranks in the following skills:
        ///Athletics, Clockwork, Drive, Handguns, Intimidate, Law (any),
        ///Melee (Balanced), Persuade, Search, Spot, Survival.
        ///Copper automatons cannot be created or upgraded with the
        ///Humanlike skin advantage.
        ///
        ///Models:
        ///Rushworth OM-86M (officer model, male)
        ///Rushwo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Copper {
            get {
                return ResourceManager.GetString("Copper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost to play: 5CP
        ///STR +1, CON +1, INT +1, CHA -1, EMP -1
        ///Initial STR and CON must be at least 10.
        ///Initial skill ranks: Craft (any) 2, First Aid 1, Knowledge:
        ///Mathematics 1
        ///15 CP can be used to buy ranks in the following skills:
        ///Alchemy, Clockwork, Craft (any), Drive, Explosives &amp;
        ///Demolitions, First Aid, Knowledge (Mathematics),
        ///Locksmithing, Mechanics, Melee (Balanced), Melee
        ///(Powerful), Steam Engineering.
        ///
        ///Craftsman automatons have been designed by craftsmen to aid
        ///craftsmen. They are equipped  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Craftsman {
            get {
                return ResourceManager.GetString("Craftsman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Crimson Empire is an isolated country in the southeastern
        ///part of the continent. Except for some trade and border
        ///skirmishes with Kheiman, Crimson people have lived in
        ///isolation from other nations for a long time, until very recently
        ///the Two Dragon Port was opened for trade and travellers from
        ///other countries. Most Crimson people lead a life without
        ///contact with other nations. Few would ever try to wander to
        ///foreign lands, for leaving the country without orders from the
        ///Emperor or shogun is puni [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Crimson {
            get {
                return ResourceManager.GetString("Crimson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STR, CON or EMP +1
        ///Initial skill ranks: Persuade 2, Animal Handling 1, Profession
        ///(farmer) 1
        ///15 CP can be used to buy ranks in the following skills:
        ///Animal handling, Brawl, Cooking, Craft (any), Listen, Melee
        ///(Balanced), Melee (Powerful), Persuade, Profession (farmer),
        ///Spot, Survival.
        ///
        ///Most people in the Crimson Empire are labourers, craftsmen
        ///and farmers living in small villages and the handful of bigger
        ///cities in the Empire. Their lifestyle is called the Way of the
        ///Land, and their work forms th [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CrimsonCommoner {
            get {
                return ResourceManager.GetString("CrimsonCommoner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STR, DEX or CHA +1
        ///Initial skill ranks: Melee (Balanced) 2, Dodge 1, Law
        ///(Crimson) 1
        ///15 CP can be used to buy ranks in the following skills:
        ///Archery, Athletics, Brawl, Craft (Blacksmithing), Negotiate,
        ///Dodge, Intimidate, Law (Crimson), Listen, Martial Art (one
        ///from Crimson), Melee (Balanced), Melee (Powerful), Persuade,
        ///Ride, Spot, Strategy/Tactics
        ///
        ///The Way of the White Dragon consists of the warriors of the
        ///Crimson Empire and their families. Most individual followers
        ///of this Way are common soldi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CrimsonMilitary {
            get {
                return ResourceManager.GetString("CrimsonMilitary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost to play: 20 CP
        ///
        ///INT +1
        ///Initial skill ranks: Law (Crimson) 3, Brawl 2, First aid 2,
        ///Martial Art (any Crimson) 2, Teaching 2, Clockwork 1, Dodge
        ///1
        ///10 CP can be used to buy ranks in the following skills:
        ///Athletics, Bargain, Brawl, Clockwork, Dodge, Diplomacy, First
        ///aid, Knowledge (any), Law (Crimson), Listen,Persuade, Martial
        ///art (one from Crimson), Melee (Balanced), Melee (Finesse),
        ///Melee (Powerful), Sense motive, Survival, Teaching,
        ///
        ///All characters of the Way of the Black Dragon have the Soc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CrimsonMonk {
            get {
                return ResourceManager.GetString("CrimsonMonk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost to play: 20 CP
        ///STR -1, CON -1, CHA +2, EMP +1
        ///Upgrade: Humanlike Skin with the Beautiful / Handsome
        ///upgrade already included.
        ///Initial skill ranks: Charm 3, Persuade 2, Athletics 1
        ///10 CP can be used to buy ranks in the following skills:
        ///Athletics, Bluff, Charm, Negotiate, Dodge, Etiquette, First Aid,
        ///Perform (Acting), Perform (Dancing), Persuade, Sense Motive.
        ///
        ///Models:
        ///Rushworth CM-54M (civilian model, male)
        ///Rushworth CM-54F (civilian model, female)
        ///Colman Inc CLD-04M Doll, commonly referred [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Doll {
            get {
                return ResourceManager.GetString("Doll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHA -2, REF +1; allocate +1 to one of the following: STR,
        ///CON or DEX
        ///
        ///Dracosaurians receive a -3 penalty to Listen rolls, a +2 bonus to
        ///Spot rolls and a +2 bonus to survival when able to track using
        ///their sense of smell.
        ///
        ///Cold-blooded: The character’s body cannot control her body
        ///temperature automatically, but needs external means to keep it
        ///on optimised level. In very cold temperatures (around and
        ///under -10°C if the character has clothing to keep himself
        ///warm), she enters a comatose state. In co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Dracosaurian {
            get {
                return ResourceManager.GetString("Dracosaurian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT +1
        ///Initial skill ranks: Survival 2, First Aid 1, Swim 1
        ///15 CP can be used to buy ranks in the following skills:
        ///Alchemy, Animal Handling, Climb, First Aid, Knowledge
        ///(Botany), Knowledge (Mathematics), Knowledge (Zoology),
        ///Language (Kheiman), Language (Victoran), Martial art
        ///(Kheiman spear), Medicine and surgery, Melee (Powerful),
        ///Sailing, Survival, Swim, Teaching, or to the Bilingual and
        ///Animal Empathy advantages.
        ///
        ///The island of Pelethok was formerly part of Kheiman, but when
        ///the Free Islands [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DracosaurianBack {
            get {
                return ResourceManager.GetString("DracosaurianBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Free Islands is the only democratic republic in Erthair. It is
        ///a very young country, having gained its independence at the
        ///end of the 80 Year War. This is strongly reflected in the lives of
        ///those who have been born and raised here.
        ///Many call the Free Islands the land of opportunities and the
        ///land of freedom. Those with the skill and cunning can make
        ///their fortunes among the Isles, for here a person’s success is not
        ///measured by their heritage or social class but by their ability to
        ///seize the oppo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FreeIsland {
            get {
                return ResourceManager.GetString("FreeIsland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any attribute +1
        ///Initial skill ranks: Athletics 1, Negotiate 1, Persuade 1, Sailing
        ///1, Sense Motive 1
        ///15 CP can be used to buy ranks in the following skills:
        ///Appraise, Athletics, Bluff, Brawl, Craft (any), Navigation,
        ///Melee (any), Negotiate, Perform (Dancing), Persuade, Sailing,
        ///Sailing (Airship), Sense Motive, Spot, Survival.
        ///
        ///The Free Islands consists of a large group of islands, and each
        ///island has its own traditions and customs. The Free Islands is a
        ///rather young nation, and the only democrati [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FreeIslandFolk {
            get {
                return ResourceManager.GetString("FreeIslandFolk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Although this island is dominated by Dracosaurians, some
        ///humans inhabit the island as well. A human character with this
        ///background uses the rules for the Dracosaurian mutant
        ///background as her background, with the exception that humans
        ///cannot take the Animal Empathy advantage.        ///.
        /// </summary>
        public static string FreePelethok {
            get {
                return ResourceManager.GetString("FreePelethok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REF, WIT or CHA +1
        ///Initial skill ranks: Sailing or Sailing (Airship) 2, Bluff 1, Brawl 1
        ///15 CP can be used to buy ranks in the following skills:
        ///Athletics, Bluff, Brawl, Craft (Gunsmithing), Handguns,
        ///Intimidate, Melee (Finesse), Navigation, Persuade, Sailing,
        ///Sailing (Airship), Sense Motive, Sleight of Hand, Spot, Stealth
        ///The seas surrounding the Free Islands are crowded with traders
        ///and travellers, as well as those making a living by preying on
        ///them. Piracy is a growing threat for the development  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FreePirate {
            get {
                return ResourceManager.GetString("FreePirate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STR +3, CON +3, REF -2, INT -2, WIT -2, CHA -2
        ///Initial STR and CON must be at least 10.
        ///Disadvantage: Sterile.
        ///
        ///All mutants have the social status: mutie disadvantage and
        ///must purchase a mutant disadvantage worth at least 3 CP to
        ///represent that no mutant is born perfect.
        ///
        ///Goliaths were originally mutants created in Wulffgartian war
        ///laboratories during the 80 Year War as an attempt to create
        ///super soldiers. They were mutated from humans who already
        ///possessed great strength and constitution. Drugs  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Goliath {
            get {
                return ResourceManager.GetString("Goliath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CON +1, CHA -1
        ///Initial skill ranks: None.
        ///10 CP can be used to buy ranks in any combat skills except
        ///Martial Arts other than Wolfbite and Northern Bladesmastery.
        ///
        ///
        ///The Goliaths born in laboratories are trained to be
        ///warmachines, not people. They have no real childhood, as they
        ///are trained to become soldiers from infancy. All their basic
        ///needs are well covered, and it is made sure that they are raised
        ///in the best possible environment to grow physically healthy and
        ///strong. Different sport activitie [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GoliathBack {
            get {
                return ResourceManager.GetString("GoliathBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grapling.
        /// </summary>
        public static string Grapling {
            get {
                return ResourceManager.GetString("Grapling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hanseburg is a small but very wealthy state neighbouring both
        ///Victora and Wulffgart. Hanseburg managed to remain neutral
        ///during the 80 Year War, trading with both countries and, when
        ///necessary, occasionally granting them free passage through
        ///their lands. This has led to close knit but cool relations with
        ///both countries. Hanseburg is the centre of trade in Erthair, and
        ///many rich merchants from other countries have chosen do
        ///deposit their wealth to Hanseburgian banks for safekeeping,
        ///which has made Ha [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Hanseburg {
            get {
                return ResourceManager.GetString("Hanseburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “Hanseburgian craftsmen boast with their skillful works and the
        ///nobles boast with the rich nation. But should they ever forget
        ///that it is the merchants who sell the craftsmen’s works and
        ///collect the riches for the country, the nation will fall.” - a head
        ///of a Hanseburgian merchant family
        ///
        ///DEX, WIT or CHA +1
        ///Initial skill ranks: Appraise 2, Negotiate 1, Persuade 1
        ///15 CP can be used to buy ranks in the following skills:
        ///Appraise, Bluff, Cooking, Craft (any), Etiquette, Intimidate,
        ///Martial Arts (Fenc [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HanseburgMerchant {
            get {
                return ResourceManager.GetString("HanseburgMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost to play: 20CP
        ///DEX, CHA or EMP +1
        ///Initial skill ranks: Appraise 2, Charm 2, Negotiate 2, Etiquette 1.
        ///Advantage: Noble, Hanseburg
        ///Starting wealth level: Drifter. This can be further raised with CP
        ///during character creation.
        ///15 CP can be used to buy ranks in the following skills:
        ///Appraise, Art (any), Charm, Etiquette, Knowledge (Heraldry),
        ///Language (Victoran), Language (Wulffgartian), Martial Arts
        ///(Fencing), Martial Arts (Hanseburgian Musketeer Fencing),
        ///Melee (Finesse), Negotiate, Perform (Dan [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HanseburgNoble {
            get {
                return ResourceManager.GetString("HanseburgNoble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CON, INT or EMP +1
        ///Initial skill ranks: Craft (any) or Profession (any) 2, Appraise 1,
        ///Persuade 1
        ///15 CP can be used to buy ranks in the following skills:
        ///Appraise, Brawl, Clockwork, Cooking, Craft (any), Negotiate,
        ///Drive, Locksmithing, Mechanics, Melee (Powerful), Persuade,
        ///Profession (any), Ride.
        ///
        ///Hanseburg is known for its craftsmanship, design, inventions
        ///and top class modern steam technology. This naturally creates a
        ///need for not only lots of factory workers and miners, but also
        ///for skilled c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HanseburgWorker {
            get {
                return ResourceManager.GetString("HanseburgWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost to play: 5 CP
        ///STR +3, CON +3, DEX -2, REF -2, CHA -1, EMP -2
        ///Initial STR and CON must be at least 12.
        ///Upgrade: Medium Plating, AV 4
        ///Gorilla punch: Heavy worker fist damage deals d6+1 points of
        ///damage. (x CP)
        ///Forklift: Heavy worker can lift and carry three times the normal
        ///amount for its STR+CON.
        ///10 CP can be used to buy ranks in the following skills: Craft
        ///(any), Mechanics, Melee (Powerful), Search, Spot, Steam
        ///Engineering, or to the Upgraded Automaton advantage.
        ///Heavy Worker automatons cann [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HeavyWorker {
            get {
                return ResourceManager.GetString("HeavyWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humans receive 10 extra CP for purchasing skills and
        ///advantages from their Background during character creation.
        ///Humans come from various backgrounds and nationalities, so
        ///their appearance and style varies widely, from the tall muscular
        ///Wulffgartian in his gray greatcoat to the tender Crimson lady in
        ///her colorful kimono. Humans are by far the dominant race of
        ///Erthair, as mutants are descended from humans and automatons
        ///are created by humans. Because of this, many humans consider
        ///themselves as the on [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Human {
            get {
                return ResourceManager.GetString("Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CON +2, CHA -2
        ///Advantage: low light vision
        ///Advantage: mule
        ///Disadvantage: slow
        ///
        ///All mutants have the social status: mutie disadvantage and
        ///must purchase a mutant disadvantage worth at least 3 CP to
        ///represent that no mutant is born perfect.
        ///
        ///These short and stout people originate from the northern
        ///mountains of Wulffgart. They are the descendants of people
        ///who lived in an old mining town of Kharzul. Almost 200 years
        ///ago a source of radiation present in the area started to change
        ///the people. Childr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KharzulDwarf {
            get {
                return ResourceManager.GetString("KharzulDwarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT +1
        ///Initial skill ranks: Profession: Mining 2, Craft (any) 1, Craft
        ///(Blacksmithing or Gunsmithing) 1
        ///10 CP can be used to buy ranks in the following skills: Bargain,
        ///Brawl, Climb, Clockwork, Cooking, Craft (any), Drive,
        ///Explosives &amp; Demolitions, Intimidate, Locksmithing, Long
        ///guns, Martial Art (Wolfbite), Melee (Balanced), Melee
        ///(Powerful), Mechanics, Profession (Mining), Steam
        ///Engineering
        ///
        ///
        ///Kharzul Dwarves must also choose one of the Wulffgart
        ///Military Service background options.
        ///The Kharzu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KharzulDwarfBack {
            get {
                return ResourceManager.GetString("KharzulDwarfBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life in Kheiman is strongly influenced and regulated by their
        ///religion. As the state and the church in Kheiman are virtually
        ///one entity, the laws and traditions in Kheiman are mostly those
        ///enacted by the church.
        ///Kheiman has an expansive education system, and so every child
        ///in Kheiman receives basic education and the opportunity to
        ///educate themselves further in some way. The literacy rate in
        ///Kheiman is the highest among the countries in Erthair.
        ///Kheiman people are divided into three classes: workers, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Kheiman {
            get {
                return ResourceManager.GetString("Kheiman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT, WIT, EMP or CHA +1
        ///Initial skill ranks: Knowledge: Kheiman religion 2, Negotiate 1,
        ///Language: Kheiman 1.
        ///15 CP can be used to buy ranks in the following skills:
        ///Alchemy, Art (any), Clockwork, Negotiate, Etiquette, First Aid,
        ///Knowledge (any), Law (Kheiman), Leadership, Mechanics,
        ///Medicine and surgery, Persuade, Teaching, or to improve the
        ///Starting wealth level.
        ///
        ///The children with intellectual tendencies, high social
        ///intelligence and skills in science are chosen to the Kheiman
        ///clergy class. Al [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KheimanClergy {
            get {
                return ResourceManager.GetString("KheimanClergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STR, DEX or WIT +1
        ///Initial skill ranks: Melee (Powerful) 2, Knowledge (Kheiman
        ///religion) 1, Martial Arts (Kheiman spear) 1
        ///15 CP can be used to buy ranks in the following skills:
        ///Athletics, Block, Brawl, Craft (Blacksmithing), Gunsmithing,
        ///Law (Kheiman), Leadership, Listen, Long Guns, Martial Arts
        ///(Kheiman spear), Ride, Spot, Survival, Throw, Melee
        ///(Powerful).
        ///
        ///The people chosen for warrior class are those whose physical
        ///abilities, courage and ability to follow orders stood out during
        ///childhood.  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KheimanWarior {
            get {
                return ResourceManager.GetString("KheimanWarior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STR, CON or INT +1
        ///Initial skill ranks: Craft or Profession (any) 2, Knowledge
        ///(Kheiman religion) 1, Art (any) 1
        ///15 CP can be used to buy ranks in the following skills: Art
        ///(any), Athletics, Brawl, Craft (any), Dodge, Mechanics,
        ///Perform (Dancing), Persuade, Profession (any), Survival.
        ///
        ///The most populous class in Kheiman is the worker class.
        ///Workers are the manual labourers of Kheiman: farmers,
        ///craftsmen, miners and factory workers, to mention but a few.
        ///Both the physically strong and the nimble ha [rest of string was truncated]&quot;;.
        /// </summary>
        public static string KheimanWorker {
            get {
                return ResourceManager.GetString("KheimanWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kriittinen onnistuminen (%): .
        /// </summary>
        public static string kriittinen {
            get {
                return ResourceManager.GetString("kriittinen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string New_Text_Document {
            get {
                return ResourceManager.GetString("New_Text_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taitoheiton onnistuminen (%):.
        /// </summary>
        public static string onnistuminen {
            get {
                return ResourceManager.GetString("onnistuminen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STR -1, DEX +1
        ///
        ///Sylphs can jump twice as high and far as humans.
        ///Sylphs gain a +1 racial bonus to dodge and athletics. The dodge
        ///bonus counts as a rank in the dodge skill for increasing PDM.
        ///Disadvantage: Frail
        ///
        ///All mutants have the social status: mutie disadvantage and
        ///must purchase a mutant disadvantage worth at least 3 CP to
        ///represent that no mutant is born perfect.
        ///
        ///Sylphs are a group of people living in the northern mountains
        ///of the Crimson Empire. It is unknown when the mutations
        ///began, b [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Sylph {
            get {
                return ResourceManager.GetString("Sylph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REF +1
        ///Initial skill ranks: Athletics 2, Climb 1, Survival 1
        ///15 CP can be used to buy ranks in the following skills: Animal
        ///Handling, Archery, Athletics, Brawl, Climb, Listen, Melee
        ///(Balanced), Perform (Singing), Sense Motive, Spot, Survival,
        ///Stealth, Throw or to the Acute Sense of Direction and Animal
        ///Empathy advantages.
        ///
        ///
        ///On the slopes of the tallest of the northern mountains of
        ///Crimson Empire live the secluded Sylphs, whose culture can be
        ///traced back centuries. Sylphs have a unique rapport wit [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SylphBack {
            get {
                return ResourceManager.GetString("SylphBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skillit
        ///- nimet
        ///- listalliset taidot matkaan mukaan..
        ///- ammattitaidot osio
        ///
        ///Attribuutit
        ///
        ///Taustat
        ///- päivitä tekstitiedostot nykyisen säännöstön mukaisiksi
        ///- päivitä taustojen boonukset nykyisen säännöstön mukaisiksi
        ///
        ///Advantage&amp;&amp;disadvantage
        ///- kaikki
        ///
        ///Tietokanta
        ///- id ylös, kun new nappulaa painetaan
        ///- save update lauseella
        ///- load ominaisuus pelaajan nimellä
        ///
        ///
        ///Dokumentaatio
        ///- Dokumentaatio, Dokumentaatio.
        /// </summary>
        public static string todo {
            get {
                return ResourceManager.GetString("todo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unburd. Carry.
        /// </summary>
        public static string UnburdCarry {
            get {
                return ResourceManager.GetString("UnburdCarry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life in Victora can be very different depending on where you
        ///were born. The social class structure in the feudal Victora is
        ///very rigid. The nobles, nowadays together with rich merchants
        ///and industrialists, direct the country, leaving the common folk
        ///with little freedom of choice. Things are stirring in Victora
        ///though, as rebellion is rising in many areas. The Workers Union
        ///movement is gaining momentum, trying to improve the
        ///working conditions and salary of common workers. The
        ///Women’s Rights movement [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Victora {
            get {
                return ResourceManager.GetString("Victora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEX, INT or WIT +1
        ///Initial skill ranks: Appraise 2, Persuade 1, Negotiate 1
        ///15 CP can be used to buy ranks in the following skills:
        ///Appraise, Bluff, Brawl, Craft (any), Cooking, Negotiate,
        ///Etiquette, Handguns, Intimidate, Martial Arts (Victoran
        ///Pugilism), Mechanics, Perform (dancing), Persuade, Profession
        ///(any), Ride.
        ///
        ///The Victoran middle class lead more prosperous lives than the
        ///lower class, but lack the status of the upper class. So, as the
        ///upper class still looks down on them as commoners, the  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VictoraMiddle {
            get {
                return ResourceManager.GetString("VictoraMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CON, REF or EMP +1
        ///Initial skill ranks: Survival 2, Brawl 1, Stealth 1
        ///15 CP can be used to buy ranks in the following skills:
        ///Athletics, Animal Handling, Bluff, Brawl, Cooking, Dodge,
        ///First Aid, Forgery, Gaming, Grappling, Handguns, Intimidate,
        ///Listen, Melee (Balanced), Melee (Powerful), Spot, Stealth,
        ///Survival, Throw or to purchase up to 10 CP worth of acquirable
        ///advantages.
        ///Starting Wealth level cannot be higher than ‘Well off’.
        ///
        ///One of the the toughest fates in Victora is to be born into a
        ///lo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VictoranLow {
            get {
                return ResourceManager.GetString("VictoranLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost to play: 10CP
        ///INT or CHA +1
        ///Initial skill ranks: Etiquette 3, Negotiate 2, Language: Victoran
        ///1
        ///The Starting wealth level of Victoran upper class characters
        ///must be Drifter or higher. The 5 CP cost of Drifter has already
        ///been calculated into the Background cost and can be further
        ///increased with CP during character creation.
        ///15 CP can be used to buy ranks in the following skills: Art
        ///(any), Charm, Negotiate, Etiquette, Knowledge: Heraldry,
        ///Language (Victoran), Long Guns, Martial Arts (Fencing) [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VictoraUpper {
            get {
                return ResourceManager.GetString("VictoraUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The military governs so much of the life in Wulffgart that the
        ///lives of its citizens are largely defined by their military service.
        ///Around 95% of the men and around 70% of the women in
        ///Wulffgart serve their country in military service. The service
        ///takes one year. Men are required to enlist at the age of 16.
        ///Women have the option for non-military service and usually
        ///work as medical help, cooks or aid the army some other way
        ///during this service. If a woman already has children or is
        ///pregnant, she can  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WolffgartService {
            get {
                return ResourceManager.GetString("WolffgartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wulffgart went through a major change 16 years ago, when
        ///Tzar Ivan the Fourth was overthrown from power and Marshal
        ///General Friedrich Krause rose to rule the nation. The military
        ///has been leading Wulffgart ever since and changing its political
        ///structure in major ways. most of the lands and wealth of
        ///Wulffgartian nobility was confiscated by the military
        ///government, and the nobles are nowadays little more than
        ///Wulffgartian commoners with glorified titles. Military service
        ///shapes the lives of Wulffgart [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Wolfgart {
            get {
                return ResourceManager.GetString("Wolfgart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STR or DEX +1
        ///Initial skill ranks: Law: Wulffgart 2, Etiquette 1, Intimidate 1.
        ///10 CP can be used to buy ranks in the following skills: Animal
        ///Handling, Athletics, Brawl, Craft (Gunsmithing), Explosives &amp;
        ///Demolitions, First Aid, Handguns, Intimidate, Law (Wulffgart),
        ///Leadership, Long Guns, Martial Arts (Wolfbite), Melee
        ///(Powerful), Ride, Stealth, Strategy/Tactics.
        ///
        ///In the eyes of the current rulers of Wulffgart, the military is the
        ///most honoured class of the nation. Military leaders are currently
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WolfgartMilitary {
            get {
                return ResourceManager.GetString("WolfgartMilitary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INT or CHA +1
        ///Initial skill ranks: Etiquette 2, Negotiate 1, Language:
        ///Wulffgartian 1
        ///10 CP can be used to buy ranks in the following skills: Charm,
        ///Negotiate, Etiquette, Intimidate, Language (Wulffgartian), Law
        ///(Wulffgart), Long Guns, Perform (Dancing), Perform (Oratory),
        ///Ride, or to improve the Starting wealth level or to purchase the
        ///Noble, Wulffgartian advantage.
        ///
        ///Members of the Wulffgartian upper class used to be the leaders
        ///of their nation and those who were respected by everyone. After
        ///the [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WolfgartUpper {
            get {
                return ResourceManager.GetString("WolfgartUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STR, CON or INT +1
        ///Initial skill ranks: Craft (Gunsmithing 2), Craft (any) 1,
        ///Mechanics 1
        ///10 CP can be used to buy ranks in the following skills: Animal
        ///Handling, Brawl, Clockwork, Cooking, Craft (any), Drive, 
        ///First Aid, Locksmithing, Mechanics, Persuade, Profession (any),
        ///Ride.
        ///
        ///The life of Wulffgartian workers has improved since the feudal
        ///days. The fruits of their labour are vital to the army, so their pay
        ///has increased, even though they are still expected to work as
        ///long and as hard as befor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WolfgartWorker {
            get {
                return ResourceManager.GetString("WolfgartWorker", resourceCulture);
            }
        }
    }
}
